[package]
name = "rust-2021-fundamentals"
version = "0.1.0"
edition = "2021"

[lib]
#name = "rust_syntax"
#path = "src/lib.rs"

name = "wbc"
path = "src/lib_module.rs"

[[bin]]
name = "test"
path = "src/main.rs"

[dependencies]
